### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by EdgarWright** [smakosh/gatsby-portfolio-dev#5]
Anyone else is getting this error?

GraphQL Error Encountered 1 error(s):
- Unknown field 'github' on type 'Query'. 

      file: ./gatsby-portfolio/new/gatsby-portfolio-dev/src/components/landing/Projects/index.jsx

**Comment by smakosh** [comment]
Have you added the env variables mentioned on the docs?

**Comment by smakosh** [comment]
The issue is caused by the `gatsby-source-graphql`, I provided more info to them, hopefully it will be fixed.

**Comment by smakosh** [comment]
Meanwhile, downgrade your gatsby and gatsby-source-graphql to a previous version and give it a try.

**Comment by smakosh** [comment]
Fixed here: https://github.com/gatsbyjs/gatsby/pull/14665

**Comment by smakosh** [comment]
It has been fixed @EdgarWright

**Comment by marclundgren** [comment]
I'm still experiencing the same problem when cloning the repo and running `yarn && yarn start` :/

**Comment by smakosh** [comment]
I just tried and everything seems to work just fine. You probably forgot the GitHub token as env variable.
